// Generated by CoffeeScript 1.10.0
(function() {
  var EventEmitter, Header, Parser, fs,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('events').EventEmitter;

  Header = require('./header');

  fs = require('fs');

  Parser = (function(superClass) {
    extend(Parser, superClass);

    function Parser(filename) {
      this.filename = filename;
      this.parseField = bind(this.parseField, this);
      this.parseRecord = bind(this.parseRecord, this);
      this.resume = bind(this.resume, this);
      this.pause = bind(this.pause, this);
      this.parse = bind(this.parse, this);
    }

    Parser.prototype.parse = function() {
      this.emit('start', this);
      this.header = new Header(this.filename);
      this.header.parse((function(_this) {
        return function(err) {
          var bufLoc, loc, overflow, sequenceNumber, stream;
          _this.emit('header', _this.header);
          sequenceNumber = 0;
          loc = _this.header.start;
          bufLoc = _this.header.start;
          overflow = null;
          _this.paused = false;
          stream = fs.createReadStream(_this.filename);
          _this.readBuf = function() {
            var buffer;
            if (_this.paused) {
              _this.emit('paused');
              return;
            }
            while (buffer = stream.read()) {
              if (bufLoc !== _this.header.start) {
                bufLoc = 0;
              }
              if (overflow !== null) {
                buffer = overflow + buffer;
              }
              while (loc < (_this.header.start + _this.header.numberOfRecords * _this.header.recordLength) && (bufLoc + _this.header.recordLength) <= buffer.length) {
                _this.emit('record', _this.parseRecord(++sequenceNumber, buffer.slice(bufLoc, bufLoc += _this.header.recordLength)));
              }
              loc += bufLoc;
              if (bufLoc < buffer.length) {
                overflow = buffer.slice(bufLoc, buffer.length);
              } else {
                overflow = null;
              }
              return _this;
            }
          };
          stream.on('readable', _this.readBuf);
          return stream.on('end', function() {
            return _this.emit('end');
          });
        };
      })(this));
      return this;
    };

    Parser.prototype.pause = function() {
      return this.paused = true;
    };

    Parser.prototype.resume = function() {
      this.paused = false;
      this.emit('resuming');
      return this.readBuf();
    };

    Parser.prototype.parseRecord = function(sequenceNumber, buffer) {
      var field, fn, i, len, loc, record, ref;
      record = {
        '@sequenceNumber': sequenceNumber,
        '@deleted': (buffer.slice(0, 1))[0] !== 32
      };
      loc = 1;
      ref = this.header.fields;
      fn = (function(_this) {
        return function(field) {
          return record[field.name] = _this.parseField(field, buffer.slice(loc, loc += field.length));
        };
      })(this);
      for (i = 0, len = ref.length; i < len; i++) {
        field = ref[i];
        fn(field);
      }
      return record;
    };

    Parser.prototype.parseField = function(field, buffer) {
      var value;
      value = (buffer.toString('utf-8')).replace(/^\x20+|\x20+$/g, '');
      if (field.type === 'N') {
        value = value === +value && value === (value|0) ? parseInt(value) : parseFloat(value, 10);
      }
      return value;
    };

    return Parser;

  })(EventEmitter);

  module.exports = Parser;

}).call(this);
