// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, Header, Parser, fs,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Header = require('./header');

  fs = require('fs');

  Parser = (function(_super) {
    __extends(Parser, _super);

    function Parser(filename) {
      this.filename = filename;
      this.parseField = __bind(this.parseField, this);
      this.parseRecord = __bind(this.parseRecord, this);
      this.parse = __bind(this.parse, this);
    }

    Parser.prototype.parse = function() {
      var _this = this;

      this.emit('start', this);
      this.header = new Header(this.filename);
      this.header.parse(function(err) {
        var sequenceNumber;

        _this.emit('header', _this.header);
        sequenceNumber = 0;
        return fs.readFile(_this.filename, function(err, buffer) {
          var loc;

          if (err) {
            throw err;
          }
          loc = _this.header.start;
          while (loc < (_this.header.start + _this.header.numberOfRecords * _this.header.recordLength) && loc < buffer.length) {
            _this.emit('record', _this.parseRecord(++sequenceNumber, buffer.slice(loc, loc += _this.header.recordLength)));
          }
          return _this.emit('end', _this);
        });
      });
      return this;
    };

    Parser.prototype.parseRecord = function(sequenceNumber, buffer) {
      var field, loc, record, _fn, _i, _len, _ref,
        _this = this;

      record = {
        '@sequenceNumber': sequenceNumber,
        '@deleted': (buffer.slice(0, 1))[0] !== 32
      };
      loc = 1;
      _ref = this.header.fields;
      _fn = function(field) {
        return record[field.name] = _this.parseField(field, buffer.slice(loc, loc += field.length));
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        _fn(field);
      }
      return record;
    };

    Parser.prototype.parseField = function(field, buffer) {
      var value;

      value = buffer.toString().replace(/^\x20+|\x20+$/g, '');
      if (field.type === 'N') {
        value = parseFloat(value);
      }
      return value;
    };

    return Parser;

  })(EventEmitter);

  module.exports = Parser;

}).call(this);
